export const XP_REWARDS = {
  HABIT_COMPLETE_DAILY: 15,
  HABIT_COMPLETE_SHARED: 20,
  HABIT_PARTNER_SYMPATHY: 5,
  HABIT_STREAK_7_DAY: 100,
  HABIT_STREAK_30_DAY: 500,
  FOCUS_POMODORO: 30,
  FOCUS_LONG_SESSION: 70,
  FOCUS_COUPLE_SESSION: 50,
  CALENDAR_EVENT_CREATE: 5,
  COUPLE_STREAK_DAY: 25,
  COUPLE_LINK: 75,
  ONBOARDING_COMPLETE: 50,
  FIRST_HABIT_OF_DAY: 10,
} as const;

export const COIN_REWARDS = {
  HABIT_COMPLETE_DAILY: 3,
  HABIT_COMPLETE_SHARED: 5,
  HABIT_PARTNER_SYMPATHY: 1,
  HABIT_STREAK_7_DAY: 20,
  HABIT_STREAK_30_DAY: 100,
  FOCUS_POMODORO: 6,
  FOCUS_LONG_SESSION: 15,
  FOCUS_COUPLE_SESSION: 10,
  CALENDAR_EVENT_CREATE: 1,
  COUPLE_STREAK_DAY: 5,
  COUPLE_LINK: 15,
  ONBOARDING_COMPLETE: 10,
  FIRST_HABIT_OF_DAY: 2,
} as const;

export type XpReason = keyof typeof XP_REWARDS;
